version: '3.5'

services:

  postgres:
    container_name: postgres_tasks_spring
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped